// Typelizer digest 28f23f46df73036547418770a085eacb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Farm} from '@/types'

type AdminGroup = {
  id: number;
  name: string;
  use_model_precip: boolean;
  members: Array<{ id: number; email: string; owner: boolean }>;
  farms: Array<Farm>;
}

export type { AdminGroup };
