// Typelizer digest bb7fdcb1cc86c5e3d26118b4b20775f8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AdminUserDetail = {
  id: number;
  email: string;
  first_name: string | null;
  last_name: string | null;
  unit_system: 'imperial' | 'metric';
  admin: boolean;
  unconfirmed_email: string | null;
  sign_in_count: number;
  created_at: string;
  updated_at: string;
  confirmed_at: string | null;
  confirmation_sent_at: string | null;
  current_sign_in_at: string | null;
  last_sign_in_at: string | null;
  current_sign_in_ip: string | null;
  last_sign_in_ip: string | null;
  remember_created_at: string | null;
  reset_password_sent_at: string | null;
  digest: boolean;
  digest_sent_on: string | null;
  display_name: string;
}

export type { AdminUserDetail };
