// Typelizer digest 0679874e6e2f56b7b7d9202e08a10c90
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AdminUser = {
  id: number;
  email: string;
  admin: boolean;
  created_at: string;
  current_sign_in_at: string | null;
  display_name: string;
  confirmed: boolean;
  farms_count: number;
  pivots_count: number;
  fields_count: number;
}

export type { AdminUser };
