// Typelizer digest 7aaa49879a0b82334157118ba1bb4f79
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Farm} from '@/types'

type AdminGroup = {
  id: number;
  name: string;
  use_model_precip: boolean;
  members: Array<{ id: number; email: string; admin: boolean }>;
  farms: Array<Farm>;
}

export type { AdminGroup };
