// Typelizer digest 01b43bb0e666814b824c70bf24eddbfd
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Pivot} from '@/types'

type Farm = {
  id: number;
  name: string;
  notes: string | null;
  pivots: Array<Pivot>;
}

export type { Farm };
