// Typelizer digest d064de00466bee61ea4061137729f953
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Planting} from '@/types'

type Field = {
  id: number;
  pivot_id: number;
  name: string;
  area_acres: number | null;
  soil_type_id: number;
  field_capacity: number | null;
  perm_wilting_pt: number | null;
  notes: string | null;
  soil_type_name: string;
  effective_field_capacity: number;
  effective_perm_wilting_pt: number;
  plantings: Array<Planting>;
}

export type { Field };
