// Typelizer digest a8b79a840b78d1c877b32576c594c340
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Planting} from '@/types'

type Field = {
  id: number;
  pivot_id: number;
  name: string;
  area_acres: number | null;
  soil_type_id: number;
  field_capacity: number | null;
  perm_wilting_pt: number | null;
  notes: string | null;
  use_model_precip: boolean | null;
  soil_type_name: string;
  effective_field_capacity: number;
  effective_perm_wilting_pt: number;
  plantings: Array<Planting>;
}

export type { Field };
