// Typelizer digest 8fcab2b3c4450d0d99cd3cd0128251b3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type FieldDay = {
  date: string;
  et0: number | null;
  et0_source: 'model' | 'missing';
  adj_et: number | null;
  et_source: 'computed' | 'gap_fill' | 'missing';
  rain: number | null;
  rain_source: 'entered' | 'pivot' | 'group' | 'model' | 'none' | 'missing';
  rain_model: number | null;
  irrigation: number | null;
  irrigation_source: 'entered' | 'pivot' | 'group' | 'model' | 'none' | 'missing';
  pivot_inches: number | null;
  soil_moisture_pct: number | null;
  moisture_source: 'entered' | 'group' | null;
  canopy: number;
  canopy_entered: number | null;
  ad: number;
  pct_moisture: number;
  deep_drainage: number;
  notes: string | null;
}

export type { FieldDay };
