// Typelizer digest 5987f8fc2f4390de3a1d346d9a5bf8e4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type FieldGroup = {
  id: number;
  name: string;
  field_ids: Array<number>;
}

export type { FieldGroup };
