// Typelizer digest ed7995318e00219e6cb8e122444c934d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Group = {
  id: number;
  name: string;
  use_model_precip: boolean;
}

export type { Group };
