// Typelizer digest d1d318ce90f239806bbdd152c11a32a2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Member = {
  id: number;
  user_id: number;
  owner: boolean;
  created_at: string;
  name: string | null;
  email: string;
}

export type { Member };
