// Typelizer digest 27e6a6ef40d50f01af07eafd2bf36dc5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Field} from '@/types'

type Pivot = {
  id: number;
  farm_id: number;
  name: string;
  latitude: number;
  longitude: number;
  radius_ft: number | null;
  arc_start_deg: number | null;
  arc_end_deg: number | null;
  equipment: string | null;
  pump_capacity_gpm: number | null;
  notes: string | null;
  fields: Array<Field>;
}

export type { Pivot };
