// Typelizer digest d5e03e100153e27e50cc37d93b5bce1b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PivotIrrigation = {
  id: number;
  pivot_id: number;
  date: string;
  inches: number | null;
  run_hours: number | null;
  field_ids: Array<number> | null;
  notes: string | null;
  applied_inches: number | null;
}

export type { PivotIrrigation };
