// Typelizer digest e6f5c095a9d6cfc6fbe2be8be589a5fc
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Planting = {
  id: number;
  field_id: number;
  plant_id: number;
  variety: string | null;
  season_start: string;
  emergence_date: string;
  end_date: string;
  max_root_zone_depth: number;
  mad_frac: number;
  et_method: 'pct_cover' | 'lai';
  target_ad_pct: number | null;
  initial_moisture_pct: number | null;
  notes: string | null;
  plant_name: string;
  plant_key: string;
  canopy_curve: boolean;
  year: number;
}

export type { Planting };
