// Typelizer digest c3877fef29860a22149f6fb84c72a498
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Planting = {
  id: number;
  field_id: number;
  plant_id: number;
  variety: string | null;
  season_start: string;
  emergence_date: string;
  end_date: string;
  max_root_zone_depth: number;
  mad_frac: number;
  et_method: 'pct_cover' | 'lai';
  target_ad_pct: number | null;
  initial_moisture_pct: number | null;
  notes: string | null;
  plant_name: string;
  year: number;
}

export type { Planting };
