// Typelizer digest ece3125ec80c30216c2fe4faaff83024
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Plant = {
  id: number;
  key: string;
  name: string;
  default_max_root_zone_depth: number;
  has_canopy_curve: boolean;
}

export type { Plant };
