// Typelizer digest 8e02159e7854eff4781cac4a67ac34ab
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PlantingSummary = {
  planting_id: number;
  plant_name: string;
  variety: string | null;
  season_start: string;
  end_date: string;
  phase: 'upcoming' | 'active' | 'ended';
  status: 'full' | 'ok' | 'caution' | 'irrigate' | null;
  weather_pending: boolean;
  date: string | null;
  ad: number | null;
  pct_moisture: number | null;
  taw: number;
  ad_max: number;
  ad_pwp: number;
  target_in: number | null;
  field_capacity_pct: number;
  wilting_point_pct: number;
  pct_at_ad_zero: number;
  last_rain: { date: string; inches: number } | null;
  last_irrigation: { date: string; inches: number } | null;
  recent: Array<{ date: string; ad: number }>;
  totals: { rain: number; irrigation: number; adj_et: number; deep_drainage: number; rain_model: number; entered_rain_days: number; entered_rain: number; entered_rain_model: number };
}

export type { PlantingSummary };
