// Typelizer digest 200d833e43a98de71fdc0c7789e0b199
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PlantingSummary = {
  planting_id: number;
  plant_name: string;
  variety: string | null;
  season_start: string;
  end_date: string;
  phase: 'upcoming' | 'active' | 'ended';
  status: 'full' | 'ok' | 'caution' | 'irrigate' | null;
  weather_pending: boolean;
  date: string | null;
  ad: number | null;
  pct_moisture: number | null;
  taw: number;
  ad_max: number;
  ad_pwp: number;
  target_in: number | null;
  field_capacity_pct: number;
  wilting_point_pct: number;
  pct_at_ad_zero: number;
  last_rain: { date: string; inches: number } | null;
  last_irrigation: { date: string; inches: number } | null;
  recent: Array<{ date: string; ad: number }>;
  totals: { rain: number; irrigation: number; adj_et: number; deep_drainage: number; rain_model: number; entered_rain_days: number; entered_rain: number; entered_rain_model: number };
  threshold: number;
  crossing: { date: string; days: number; ad: number; refill: number } | null;
  use_model_precip: boolean;
  dry_crossing: { date: string; days: number; ad: number; refill: number } | null;
  ensemble_size: number;
  projection: { date: string; ad: number; p10: number | null; p50: number | null; p90: number | null; chance: number | null; dry_ad: number | null }[];
}

export type { PlantingSummary };
