// Typelizer digest 90df4e79971cd421a9f6898f9f7450ba
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type SoilType = {
  id: number;
  key: string;
  name: string;
  field_capacity: number;
  perm_wilting_pt: number;
}

export type { SoilType };
