// Typelizer digest 0404d21b25717608719da8b56791bfaf
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  email: string;
  first_name: string | null;
  last_name: string | null;
  admin: boolean;
  unit_system: 'imperial' | 'metric';
  display_name: string;
}

export type { User };
