// Typelizer digest 81f11fee6bd8de866b862581791f2662
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type WeatherCellStatus = {
  id: number;
  latitude: number;
  longitude: number;
  timezone: string | null;
  elevation_m: number | null;
  pivot_count: number;
  active: boolean;
  season_start: string | null;
  days_stored: number;
  missing_days: number | null;
  provisional_days: number;
  latest_date: string | null;
  forecast_issued_at: string | null;
  forecast_through: string | null;
  last_fetched_at: string | null;
  last_error: string | null;
  last_error_at: string | null;
}

export type { WeatherCellStatus };
