// Typelizer digest 9c3f717986a2ece71079b73f5287e12a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type WeatherPanelDay = {
  date: string;
  forecast: boolean;
  gdd: number | null;
  gdd_since_emergence: number;
  et0_in: number | null;
  precip_in: number | null;
  tmax_f: number | null;
  tmin_f: number | null;
  tmean_f: number | null;
  dew_point_f: number | null;
  rh_mean_pct: number | null;
  rh_min_pct: number | null;
  vpd_max_kpa: number | null;
  wind_speed_mph: number | null;
  wind_gust_max_mph: number | null;
  wind_direction_deg: number | null;
  cloud_cover_pct: number | null;
  soil_temp_0_7cm_f: number | null;
  soil_temp_7_28cm_f: number | null;
  soil_temp_28_100cm_f: number | null;
  soil_temp_100_255cm_f: number | null;
  soil_moisture_0_7cm: number | null;
  soil_moisture_7_28cm: number | null;
  soil_moisture_28_100cm: number | null;
  soil_moisture_100_255cm: number | null;
}

export type { WeatherPanelDay };
