// Typelizer digest 66caa21db4785fbb0ac0a07d7416b208
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** PATCH /settings/digest */
  update: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/settings/digest', {}, options),
    method: 'patch',
  }),
}
