// Typelizer digest 3c5cbc1fb5d0ae0b780d8fa85cf6c83b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export { default as adminWeather } from './Admin/WeatherController'
export { default as currentGroups } from './CurrentGroupsController'
export { default as dashboard } from './DashboardController'
export { default as magicLinks } from './MagicLinksController'
export { default as settings } from './SettingsController'
export { default as usersConfirmations } from './Users/ConfirmationsController'
export { default as usersPasswords } from './Users/PasswordsController'
export { default as usersRegistrations } from './Users/RegistrationsController'
export { default as usersSessions } from './Users/SessionsController'

import _usersRegistrations from './Users/RegistrationsController'
import _usersConfirmations from './Users/ConfirmationsController'
import _currentGroups from './CurrentGroupsController'
import _usersSessions from './Users/SessionsController'
import _usersPasswords from './Users/PasswordsController'
import _magicLinks from './MagicLinksController'
import _adminWeather from './Admin/WeatherController'
import _dashboard from './DashboardController'

export const cancelUserRegistration = _usersRegistrations.cancel
export const confirmUserConfirmation = _usersConfirmations.confirm
export const currentGroup = _currentGroups.update
export const destroyUserSession = _usersSessions.destroy
export const editUserPassword = _usersPasswords.edit
export const editUserRegistration = _usersRegistrations.edit
export const magicLink = _magicLinks.show
export const newUserConfirmation = _usersConfirmations.new
export const newUserPassword = _usersPasswords.new
export const newUserRegistration = _usersRegistrations.new
export const newUserSession = _usersSessions.new
export const redeemMagicLink = _magicLinks.redeem
export const refreshAdminWeather = _adminWeather.refresh
export const root = _dashboard.show
export const signInCode = _magicLinks.code
export const userConfirmation = _usersConfirmations.show
export const userPassword = _usersPasswords.update
export const userRegistration = _usersRegistrations.update
export const userSession = _usersSessions.create
