// Typelizer digest 5cf5f5388e7d8ba84910b078bc4a5109
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** POST /account/sign_in_link */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/account/sign_in_link', {}, options),
    method: 'post',
  }),

  /** GET /account/sign_in_link/:token */
  show: (
    params: { token: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/account/sign_in_link/:token', params, options),
    method: 'get',
  }),

  /** POST /account/sign_in_link/:token */
  redeem: (
    params: { token: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/account/sign_in_link/:token', params, options),
    method: 'post',
  }),
}
