// Typelizer digest 78174f695f5218ed5ae24289e2d7e532
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /setup */
  show: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/setup', {}, options),
    method: 'get',
  }),

  /** PATCH /setup */
  update: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/setup', {}, options),
    method: 'patch',
  }),
}
